(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(git-gutter:update-interval 2)
 '(package-selected-packages
   (quote
    (clj-refactor inf-clojure clojure-mode-extra-font-locking nrepl-eval-sexp-fu cider-eval-sexp-fu cider-decompile cider csv-mode lua-mode feature-mode geiser racket-mode macrostep pcre2el flycheck-package flycheck-cask elisp-slime-nav paxedit autodisass-llvm-bitcode llvm-mode autodisass-java-bytecode disaster change-inner smart-forward smartrep electric-case electric-spacing highlight-symbol highlight-numbers ggtags hl-sexp hl-todo eldoc-extension mvn nexus java-snippets java-imports grails-mode graphviz-dot-mode yaml-mode markdown-mode company-auctex auctex-latexmk hungry-delete typo volatile-highlights flycheck-pos-tip flycheck-color-mode-line company-web company-try-hard company-tern company-statistics company-sourcekit company-shell company-restclient company-racer company-quickhelp company-qml company-nixos-options company-math company-jedi company-irony-c-headers company-inf-ruby company-go company-ghci company-flx company-emoji company-edbi company-dcd company-cabal company-arduino company-ansible company-anaconda company adjust-parens paredit-menu paredit-everywhere paredit color-moccur color-identifiers-mode rainbow-identifiers rainbow-delimiters rainbow-mode wgrep-ag wgrep ag imenu-anywhere page-break-lines wiki-nav ace-window ace-jump-zap ace-jump-buffer ace-jump-mode smooth-scrolling nlinum undo-tree expand-region move-text multiple-cursors easy-kill zop-to-char browse-kill-ring visual-regexp adaptive-wrap launch hardhat ignoramus git-gutter-fringe+ git-gutter+ fringe-current-line writeroom-mode ibuffer-vc diffview smex flx-isearch flx-ido ido-exit-target ido-describe-bindings ido-clever-match ido-complete-space-or-hyphen ido-at-point ido-ubiquitous deft god-mode golden-ratio anzu fancy-battery stickyfunc-enhance powerline dynamic-fonts moe-theme darcula-theme unicode-fonts cus-edit+ exec-path-from-shell use-package))))
